# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_empregado_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregado',
            name='foto',
            field=models.ImageField(upload_to='cliente_fotos'),
        ),
    ]
